--
-- Script to create a database for storing Performance Counter data
--
SET NOCOUNT ON
GO
use [Master]
GO


CREATE DATABASE [Performance] ON  PRIMARY 
( NAME = N'Performance', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Performance.mdf' , SIZE = 30912KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Performance_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Performance_log.LDF' , SIZE = 24704KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'Performance', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Performance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Performance] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Performance] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Performance] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Performance] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Performance] SET ARITHABORT OFF 
GO
ALTER DATABASE [Performance] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Performance] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Performance] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Performance] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Performance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Performance] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Performance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Performance] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Performance] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Performance] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Performance] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Performance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Performance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Performance] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Performance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Performance] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Performance] SET  READ_WRITE 
GO
ALTER DATABASE [Performance] SET RECOVERY FULL 
GO
ALTER DATABASE [Performance] SET  MULTI_USER 
GO
ALTER DATABASE [Performance] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Performance] SET DB_CHAINING OFF 

if exists(select * from sys.databases where name = 'Performance')
	PRINT 'Performance database created.'

if not exists(select * from sys.databases where name='AW')
	BEGIN
	
		USE [master]
		GO

		CREATE DATABASE [AW] ON  PRIMARY 
		( NAME = N'AW_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\AW_Data.mdf' , SIZE = 35648KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
		 LOG ON 
		( NAME = N'AW_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\AW_Log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
		GO

		ALTER DATABASE [AW] SET COMPATIBILITY_LEVEL = 100
		GO

		IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
		begin
		EXEC [AW].[dbo].[sp_fulltext_database] @action = 'enable'
		end
		GO

		ALTER DATABASE [AW] SET ANSI_NULL_DEFAULT OFF 
		GO

		ALTER DATABASE [AW] SET ANSI_NULLS OFF 
		GO

		ALTER DATABASE [AW] SET ANSI_PADDING OFF 
		GO

		ALTER DATABASE [AW] SET ANSI_WARNINGS OFF 
		GO

		ALTER DATABASE [AW] SET ARITHABORT OFF 
		GO

		ALTER DATABASE [AW] SET AUTO_CLOSE OFF 
		GO

		ALTER DATABASE [AW] SET AUTO_CREATE_STATISTICS ON 
		GO

		ALTER DATABASE [AW] SET AUTO_SHRINK OFF 
		GO

		ALTER DATABASE [AW] SET AUTO_UPDATE_STATISTICS ON 
		GO

		ALTER DATABASE [AW] SET CURSOR_CLOSE_ON_COMMIT OFF 
		GO

		ALTER DATABASE [AW] SET CURSOR_DEFAULT  GLOBAL 
		GO

		ALTER DATABASE [AW] SET CONCAT_NULL_YIELDS_NULL OFF 
		GO

		ALTER DATABASE [AW] SET NUMERIC_ROUNDABORT OFF 
		GO

		ALTER DATABASE [AW] SET QUOTED_IDENTIFIER OFF 
		GO

		ALTER DATABASE [AW] SET RECURSIVE_TRIGGERS OFF 
		GO

		ALTER DATABASE [AW] SET  ENABLE_BROKER 
		GO

		ALTER DATABASE [AW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
		GO

		ALTER DATABASE [AW] SET DATE_CORRELATION_OPTIMIZATION OFF 
		GO

		ALTER DATABASE [AW] SET TRUSTWORTHY OFF 
		GO

		ALTER DATABASE [AW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
		GO

		ALTER DATABASE [AW] SET PARAMETERIZATION SIMPLE 
		GO

		ALTER DATABASE [AW] SET READ_COMMITTED_SNAPSHOT OFF 
		GO

		ALTER DATABASE [AW] SET HONOR_BROKER_PRIORITY OFF 
		GO

		ALTER DATABASE [AW] SET  READ_WRITE 
		GO

		ALTER DATABASE [AW] SET RECOVERY FULL 
		GO

		ALTER DATABASE [AW] SET  MULTI_USER 
		GO

		ALTER DATABASE [AW] SET PAGE_VERIFY CHECKSUM  
		GO

		ALTER DATABASE [AW] SET DB_CHAINING OFF 
		GO

		if exists(select * from sys.databases where name = 'AW')
			PRINT 'AW database created.'

	
	END
	

-- Add table to AW db
USE [AW]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [Sales].[Reseller](
	[City] [nvarchar](255) NULL,
	[State] [nvarchar](255) NULL,
	[PostalCode] [nvarchar](50) NULL,
	[CustomerNumber] [nvarchar](255) NULL,
	[Phone] [nvarchar](255) NULL,
	[BusinessType] [nvarchar](255) NULL,
	[ResellerName] [nvarchar](255) NULL,
	[NumberEmployees] [int] NULL,
	[OrderFrequency] [nvarchar](255) NULL,
	[FirstOrderYear] [int] NULL,
	[LastOrderYear] [int] NULL,
	[ProductLine] [nvarchar](255) NULL,
	[AddressLine1] [nvarchar](255) NULL,
	[AddressLine2] [nvarchar](255) NULL,
	[AnnualSales] [float] NULL,
	[BankName] [nvarchar](255) NULL,
	[AnnualRevenue] [int] NULL,
	[YearOpened] [int] NULL
) ON [PRIMARY]

GO

if OBJECT_ID('AW.Sales.Reseller','U') is not null
	PRINT 'Sales.Reseller table created.'


PRINT 'Script completed.'
GO

